version: "3"

# NOTE:  This compose file is for LOCAL connections on a single-user workstation ONLY

services:      
    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_DB=jwthenticator

    jwthenticator:
        image: clarotyltd/jwthenticator
        ports:
            - 8080:8080
        environment:
            - DB_NAME=jwthenticator
            - DB_HOST=postgres
        depends_on:
            - postgres
