name: Lint

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.15
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry setuptools==75.5.0
        poetry config virtualenvs.create false
        poetry install
    - name: Analysing the code with pylint + mypy
      run: |
        python -m pylint jwthenticator
        python -m mypy jwthenticator
